// Claude Design 로그인 문법을 확장한 회원가입 2열 셸과 퍼널 스타일
import * as stylex from "@stylexjs/stylex";

const DESKTOP = "@media (min-width: 768px)";
const REDUCED = "@media (prefers-reduced-motion: reduce)";

const stepEnter = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(8px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

export const styles = stylex.create({
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "clamp(16px,4vw,40px)",
    backgroundColor: "var(--hb-color-canvas)",
  },
  card: {
    width: "100%",
    maxWidth: 1000,
    minHeight: { [DESKTOP]: 640 },
    display: "grid",
    gridTemplateColumns: { default: "1fr", [DESKTOP]: "1fr 1fr" },
    overflow: "hidden",
    borderRadius: 28,
    backgroundColor: "var(--hb-color-surface)",
    boxShadow: "var(--hb-angel-shadow-lg)",
  },
  brand: {
    display: { default: "none", [DESKTOP]: "flex" },
    flexDirection: "column",
    justifyContent: "space-between",
    gap: 30,
    padding: 48,
    backgroundImage: "linear-gradient(155deg,#2E6B4E,#1B4433)",
    color: "#F2F7F2",
  },
  brandLogo: {
    display: "inline-flex",
    alignItems: "center",
    gap: 9,
    fontFamily: "var(--hb-font-display)",
    fontSize: "1.1875rem",
    fontWeight: 700,
  },
  brandLogoIcon: {
    width: 30,
    height: 30,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "rgba(242,247,242,0.18)",
  },
  brandTitle: {
    margin: 0,
    maxWidth: "24rem",
    fontFamily: "var(--hb-font-display)",
    fontSize: "1.9375rem",
    lineHeight: 1.4,
    fontWeight: 700,
    textWrap: "balance",
  },
  brandLead: {
    margin: 0,
    marginTop: 16,
    maxWidth: "24rem",
    fontSize: "0.90625rem",
    lineHeight: 1.8,
    color: "rgba(242,247,242,0.78)",
  },
  activityCard: {
    paddingBlock: 18,
    paddingInline: 18,
    borderRadius: 20,
    backgroundColor: "rgba(248, 249, 241, 0.96)",
    boxShadow: "0 18px 42px rgba(8, 35, 24, 0.18)",
    color: "var(--hb-color-text-primary)",
  },
  activityHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    paddingBottom: 13,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "rgba(27, 68, 51, 0.10)",
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "var(--hb-color-accent-dark)",
  },
  activityHeaderDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    backgroundColor: "var(--hb-angel-accent-warm)",
    boxShadow: "0 0 0 4px rgba(226, 178, 91, 0.16)",
  },
  activityList: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    margin: 0,
    padding: 0,
    paddingTop: 8,
    listStyle: "none",
  },
  activityItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    minHeight: 48,
  },
  activityIcon: {
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 36,
    height: 36,
    borderRadius: 12,
    color: "var(--hb-color-accent-dark)",
    backgroundColor: "rgba(46, 107, 78, 0.10)",
  },
  activityCopy: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  },
  activityTitle: {
    fontSize: "0.8125rem",
    lineHeight: 1.35,
  },
  activityDescription: {
    fontSize: "0.75rem",
    lineHeight: 1.45,
    color: "var(--hb-color-text-secondary)",
  },
  body: {
    paddingBlock: { default: 36, [DESKTOP]: 44 },
    paddingInline: { default: 24, [DESKTOP]: 48 },
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  progressHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "0.78125rem",
    color: "var(--hb-color-neutral)",
  },
  progress: { display: "flex", gap: 5, marginTop: 10, marginBottom: 30 },
  progressBar: {
    flex: 1,
    height: 5,
    borderRadius: "var(--hb-angel-radius-pill)",
    backgroundColor: "var(--hb-color-border)",
  },
  progressBarOn: { backgroundColor: "var(--hb-color-accent)" },
  step: {
    animationName: stepEnter,
    animationDuration: { default: "var(--hb-angel-dur-slow)", [REDUCED]: "0.01s" },
    animationTimingFunction: "var(--hb-angel-ease)",
  },
  overline: { display: "none" },
  title: {
    margin: 0,
    fontFamily: "var(--hb-font-display)",
    fontSize: "1.625rem",
    fontWeight: 700,
    letterSpacing: "-0.015em",
    color: "var(--hb-color-text-primary)",
  },
  subtitle: {
    margin: 0,
    marginTop: 9,
    marginBottom: 26,
    fontSize: "0.875rem",
    lineHeight: 1.6,
    color: "var(--hb-color-neutral)",
  },
  fields: { display: "flex", flexDirection: "column", gap: 16 },
  submit: { marginTop: 28 },
  toggle: {
    minHeight: 40,
    paddingInline: 8,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "var(--hb-color-text-secondary)",
    fontSize: "0.8125rem",
    cursor: "pointer",
  },
  footer: {
    margin: 0,
    marginTop: 22,
    textAlign: "center",
    fontSize: "0.84375rem",
    color: "var(--hb-color-neutral)",
  },
  footerLink: { fontWeight: 600, color: "var(--hb-color-accent)" },
  agreeAll: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minHeight: 48,
    padding: 16,
    marginBottom: 8,
    borderRadius: 18,
    backgroundColor: "var(--hb-angel-green-tint)",
    color: "var(--hb-color-text-primary)",
    fontSize: "0.9375rem",
    fontWeight: 700,
    cursor: "pointer",
  },
  agreeRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minHeight: 44,
    paddingBlock: 8,
    paddingInline: 4,
    fontSize: "0.875rem",
    color: "var(--hb-color-text-primary)",
    cursor: "pointer",
  },
  agreeLabel: { flex: 1 },
  agreeView: { fontSize: "0.8125rem", color: "var(--hb-color-text-secondary)" },
  optionalTag: { color: "var(--hb-color-text-secondary)", fontWeight: 500 },
});
