import { useMemo } from "react";
import { ISSUE_STATUS_ORDER, type IssueType } from "@/entities/issue";
import type { ColumnMap } from "../lib/kanban-dnd.lib";

const MOCK_ISSUES: IssueType[] = [
  {
    id: { value: "issue-1" },
    projectId: "proj-1",
    key: "HOBOM-1",
    title: "로그인 페이지 UI 구현",
    description: "",
    kind: "TASK",
    priority: "HIGH",
    status: "TODO",
    assignee: { id: "user-1", name: "김호범" },
    reporter: { id: "user-1", name: "김호범" },
    sprintId: null,
    order: 0,
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: { value: "issue-2" },
    projectId: "proj-1",
    key: "HOBOM-2",
    title: "회원가입 폼 유효성 검사",
    description: "",
    kind: "STORY",
    priority: "MEDIUM",
    status: "TODO",
    assignee: null,
    reporter: { id: "user-1", name: "김호범" },
    sprintId: null,
    order: 1,
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: { value: "issue-3" },
    projectId: "proj-1",
    key: "HOBOM-3",
    title: "대시보드 API 연동 버그 수정",
    description: "",
    kind: "BUG",
    priority: "HIGHEST",
    status: "TODO",
    assignee: { id: "user-2", name: "이범호" },
    reporter: { id: "user-1", name: "김호범" },
    sprintId: null,
    order: 2,
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: { value: "issue-4" },
    projectId: "proj-1",
    key: "HOBOM-4",
    title: "사이드바 네비게이션 리팩터링",
    description: "",
    kind: "TASK",
    priority: "MEDIUM",
    status: "IN_PROGRESS",
    assignee: { id: "user-1", name: "김호범" },
    reporter: { id: "user-1", name: "김호범" },
    sprintId: null,
    order: 0,
    createdAt: "2026-02-28T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: { value: "issue-5" },
    projectId: "proj-1",
    key: "HOBOM-5",
    title: "알림 실시간 웹소켓 연결",
    description: "",
    kind: "STORY",
    priority: "HIGH",
    status: "IN_PROGRESS",
    assignee: { id: "user-2", name: "이범호" },
    reporter: { id: "user-1", name: "김호범" },
    sprintId: null,
    order: 1,
    createdAt: "2026-02-28T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: { value: "issue-6" },
    projectId: "proj-1",
    key: "HOBOM-6",
    title: "노트 드래그 앤 드롭 순서 저장",
    description: "",
    kind: "TASK",
    priority: "LOW",
    status: "IN_REVIEW",
    assignee: { id: "user-1", name: "김호범" },
    reporter: { id: "user-2", name: "이범호" },
    sprintId: null,
    order: 0,
    createdAt: "2026-02-27T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: { value: "issue-7" },
    projectId: "proj-1",
    key: "HOBOM-7",
    title: "메뉴 추천 알고리즘 개선",
    description: "",
    kind: "EPIC",
    priority: "HIGH",
    status: "DONE",
    assignee: { id: "user-2", name: "이범호" },
    reporter: { id: "user-1", name: "김호범" },
    sprintId: null,
    order: 0,
    createdAt: "2026-02-25T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: { value: "issue-8" },
    projectId: "proj-1",
    key: "HOBOM-8",
    title: "다크 모드 테마 적용",
    description: "",
    kind: "TASK",
    priority: "LOWEST",
    status: "DONE",
    assignee: { id: "user-1", name: "김호범" },
    reporter: { id: "user-1", name: "김호범" },
    sprintId: null,
    order: 1,
    createdAt: "2026-02-24T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
];

export const useKanbanBoard = (_projectId: string) => {
  const groupedByStatus = useMemo(() => {
    const columns = Object.fromEntries(
      ISSUE_STATUS_ORDER.map((s) => [s, [] as IssueType[]]),
    ) as ColumnMap;

    for (const issue of MOCK_ISSUES) {
      columns[issue.status]?.push(issue);
    }
    return columns;
  }, []);

  return { groupedByStatus };
};
