import * as stylex from "@stylexjs/stylex";

const DESKTOP = "@media (min-width: 1024px)";

export const styles = stylex.create({
  // App shell locked to the viewport: the top bar and (mobile) bottom tab stay
  // fixed while only the content region scrolls.
  shell: {
    height: "100dvh",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "var(--hb-color-surface)",
  },

  // ── Top bar (sticky) ────────────────────────────────────
  topbar: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    backgroundColor: "rgba(251,247,240,0.90)",
    backdropFilter: "blur(12px)",
    boxShadow: "0 1px 0 rgba(34,49,42,0.06)",
  },
  topInner: {
    maxWidth: 1200,
    marginInline: "auto",
    minHeight: 58,
    display: "flex",
    alignItems: "center",
    gap: 14,
    paddingBlock: 10,
    paddingInline: "clamp(16px, 4vw, 26px)",
  },
  brand: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontFamily: "var(--hb-font-display)",
    fontWeight: 700,
    fontSize: "1.1875rem",
    color: "var(--hb-color-text-primary)",
    textDecoration: "none",
    flexShrink: 0,
  },
  primaryNav: {
    display: { default: "none", [DESKTOP]: "flex" },
    alignItems: "center",
    gap: 4,
    marginInlineStart: 6,
  },
  navLink: {
    paddingBlock: 8,
    paddingInline: 14,
    borderRadius: "var(--hb-angel-radius-pill)",
    fontSize: "0.875rem",
    fontWeight: 500,
    color: "var(--hb-color-text-secondary)",
    textDecoration: "none",
  },
  navLinkActive: {
    color: "var(--hb-color-text-primary)",
    backgroundColor: "var(--hb-color-border)",
  },
  spacer: { flex: 1 },
  searchForm: { display: "contents" },
  search: {
    display: { default: "none", [DESKTOP]: "block" },
    width: 250,
    height: 40,
    borderRadius: "var(--hb-angel-radius-pill)",
    borderWidth: 0,
    paddingInline: 16,
    fontSize: "0.84375rem",
    backgroundColor: "var(--hb-angel-surface-alt)",
  },
  actions: { display: "flex", alignItems: "center", gap: 8, flexShrink: 0 },
  iconBtn: {
    position: "relative",
    width: 36,
    height: 36,
    borderRadius: "50%",
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    fontSize: "1.1rem",
  },
  badge: {
    position: "absolute",
    top: 4,
    right: 4,
    minWidth: 16,
    height: 16,
    paddingInline: 4,
    borderRadius: 999,
    backgroundColor: "var(--hb-color-accent)",
    color: "#ffffff",
    fontSize: "0.625rem",
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Profile dropdown ────────────────────────────────────
  profileWrap: { position: "relative", display: { default: "none", [DESKTOP]: "block" } },
  profileBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    height: 38,
    paddingInline: "5px 13px",
    borderRadius: 999,
    borderWidth: 0,
    backgroundColor: "#EEE8DD",
    cursor: "pointer",
    fontSize: "0.875rem",
    fontWeight: 500,
    color: "var(--hb-color-text-primary)",
  },
  profileAvatar: {
    width: 28,
    height: 28,
    marginInlineStart: -8,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    backgroundColor: "var(--hb-color-accent)",
    color: "var(--hb-color-accent-contrast)",
    fontSize: "0.8125rem",
    fontWeight: 600,
  },
  backdrop: { position: "fixed", inset: 0, zIndex: 25 },
  menu: {
    position: "absolute",
    top: "calc(100% + 8px)",
    right: 0,
    zIndex: 30,
    minWidth: 190,
    backgroundColor: "var(--hb-color-surface)",
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    boxShadow: "var(--hb-angel-shadow)",
    padding: 6,
  },
  menuItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    paddingBlock: 9,
    paddingInline: 10,
    borderRadius: 9,
    fontSize: "0.875rem",
    color: "var(--hb-color-text-primary)",
    textDecoration: "none",
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    textAlign: "left",
  },
  menuDivider: { height: 1, backgroundColor: "var(--hb-color-border)", marginBlock: 6 },

  // ── Content + mobile bottom tab ─────────────────────────
  // The only scroll region. `min-height: 0` lets it shrink inside the flex
  // shell so its own overflow (not the body) scrolls. A column layout lets the
  // main region grow so the footer sits at the bottom on short pages.
  content: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "var(--hb-color-surface)",
    paddingBottom: { default: 64, [DESKTOP]: 0 },
  },
  // Grow to fill the content region so a short page still pushes the footer down.
  main: {
    flex: 1,
  },
  bottomTab: {
    display: { default: "flex", [DESKTOP]: "none" },
    position: "fixed",
    bottom: 0,
    insetInline: 0,
    zIndex: 20,
    minHeight: 64,
    backgroundColor: "rgba(251,247,240,0.94)",
    backdropFilter: "blur(12px)",
    boxShadow: "0 -1px 0 rgba(34,49,42,0.06)",
    paddingBlock: "9px max(14px, env(safe-area-inset-bottom))",
  },
  tab: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    fontSize: "0.6875rem",
    fontWeight: 600,
    color: "var(--hb-color-text-secondary)",
    textDecoration: "none",
  },
  tabActive: { color: "var(--hb-color-accent-dark)" },
  tabIconWrap: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 44,
    height: 26,
    borderRadius: 999,
    transitionProperty: "background-color",
    transitionDuration: "0.15s",
  },
  // The active pill (Material-3 style) makes the selected tab unmistakable.
  tabIconWrapActive: { backgroundColor: "var(--hb-angel-green-tint)" },
});
