import * as stylex from "@stylexjs/stylex";

const DESKTOP = "@media (min-width: 1024px)";

export const styles = stylex.create({
  shell: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "var(--hb-angel-surface-alt)",
  },

  // ── Top bar (sticky) ────────────────────────────────────
  topbar: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    backgroundColor: "var(--hb-color-surface)",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--hb-color-border)",
  },
  topInner: {
    maxWidth: 1200,
    marginInline: "auto",
    height: 60,
    display: "flex",
    alignItems: "center",
    gap: 12,
    paddingInline: "clamp(16px, 4vw, 32px)",
  },
  brand: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontWeight: 800,
    fontSize: "1.0625rem",
    color: "var(--hb-color-text-primary)",
    textDecoration: "none",
    flexShrink: 0,
  },
  primaryNav: {
    display: { default: "none", [DESKTOP]: "flex" },
    alignItems: "center",
    gap: 2,
    marginInlineStart: 8,
  },
  navLink: {
    paddingBlock: 8,
    paddingInline: 12,
    borderRadius: 10,
    fontSize: "0.9375rem",
    fontWeight: 600,
    color: "var(--hb-color-text-secondary)",
    textDecoration: "none",
  },
  navLinkActive: {
    color: "var(--hb-color-accent-dark)",
    backgroundColor: "var(--hb-angel-green-tint)",
  },
  spacer: { flex: 1 },
  search: {
    display: { default: "none", [DESKTOP]: "block" },
    width: 200,
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    paddingInline: 12,
    fontSize: "0.875rem",
    backgroundColor: "var(--hb-angel-surface-alt)",
  },
  actions: { display: "flex", alignItems: "center", gap: 8, flexShrink: 0 },
  iconBtn: {
    position: "relative",
    width: 38,
    height: 38,
    borderRadius: 10,
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    fontSize: "1.1rem",
  },
  badge: {
    position: "absolute",
    top: 4,
    right: 4,
    minWidth: 16,
    height: 16,
    paddingInline: 4,
    borderRadius: 999,
    backgroundColor: "var(--hb-color-accent)",
    color: "#ffffff",
    fontSize: "0.625rem",
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Profile dropdown ────────────────────────────────────
  profileWrap: { position: "relative", display: { default: "none", [DESKTOP]: "block" } },
  profileBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    height: 38,
    paddingInline: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    backgroundColor: "transparent",
    cursor: "pointer",
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "var(--hb-color-text-primary)",
  },
  backdrop: { position: "fixed", inset: 0, zIndex: 25 },
  menu: {
    position: "absolute",
    top: "calc(100% + 8px)",
    right: 0,
    zIndex: 30,
    minWidth: 190,
    backgroundColor: "var(--hb-color-surface)",
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    boxShadow: "var(--hb-angel-shadow)",
    padding: 6,
  },
  menuItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    paddingBlock: 9,
    paddingInline: 10,
    borderRadius: 9,
    fontSize: "0.875rem",
    color: "var(--hb-color-text-primary)",
    textDecoration: "none",
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    textAlign: "left",
  },
  menuDivider: { height: 1, backgroundColor: "var(--hb-color-border)", marginBlock: 6 },

  // ── Content + mobile bottom tab ─────────────────────────
  content: { flex: 1, paddingBottom: { default: 64, [DESKTOP]: 0 } },
  bottomTab: {
    display: { default: "flex", [DESKTOP]: "none" },
    position: "fixed",
    bottom: 0,
    insetInline: 0,
    zIndex: 20,
    height: 60,
    backgroundColor: "var(--hb-color-surface)",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--hb-color-border)",
    paddingBottom: "env(safe-area-inset-bottom)",
  },
  tab: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.8125rem",
    fontWeight: 600,
    color: "var(--hb-color-text-secondary)",
    textDecoration: "none",
  },
  tabActive: { color: "var(--hb-color-accent-dark)" },
});
