import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  link: {
    display: "block",
    color: "inherit",
    textDecoration: "none",
    borderRadius: "var(--hb-angel-radius-card)",
    transitionProperty: "transform, box-shadow",
    transitionDuration: "0.15s",
    transform: { default: "none", ":hover": "translateY(-2px)" },
    boxShadow: { default: "none", ":hover": "var(--hb-angel-shadow)" },
  },
  body: { paddingInline: 14, paddingTop: 12, paddingBottom: 14 },
  // Overlaps the cover's bottom edge, ringed against the card surface.
  avatar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 48,
    height: 48,
    marginTop: -36,
    marginBottom: 10,
    borderRadius: 14,
    borderWidth: 3,
    borderStyle: "solid",
    borderColor: "var(--hb-color-surface)",
    backgroundColor: "var(--hb-color-success-subtle)",
    color: "var(--hb-color-success)",
    fontSize: "1.25rem",
    fontWeight: 700,
    position: "relative",
  },
  nameRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8 },
  name: { margin: 0, fontSize: "1rem", fontWeight: 700, color: "var(--hb-color-text-primary)" },
  region: {
    margin: 0,
    marginTop: 6,
    fontSize: "0.8125rem",
    color: "var(--hb-color-text-secondary)",
  },
  cta: {
    marginTop: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    height: 38,
    borderRadius: 11,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "var(--hb-color-text-primary)",
  },
});
