// Claude Design 추천 동물 카드의 사진 슬롯·상태·정보 계층 스타일
import * as stylex from "@stylexjs/stylex";

const TABLET = "@media (min-width: 640px)";
const DESKTOP = "@media (min-width: 1024px)";

export const styles = stylex.create({
  section: {
    maxWidth: 1200,
    marginInline: "auto",
    paddingTop: 44,
    paddingInline: { default: 20, [DESKTOP]: 40 },
    backgroundColor: "var(--hb-color-surface)",
  },
  head: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 18,
  },
  title: {
    margin: 0,
    fontFamily: "var(--hb-font-display)",
    fontSize: "1.5rem",
    fontWeight: 700,
    letterSpacing: "-0.01em",
    color: "var(--hb-color-text-primary)",
  },
  more: {
    fontSize: "0.84375rem",
    fontWeight: 500,
    color: "var(--hb-color-accent)",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: { default: "repeat(2,1fr)", [TABLET]: "repeat(4,1fr)" },
    gap: 14,
  },
  card: {
    overflow: "hidden",
    borderRadius: "var(--hb-angel-radius-card)",
    backgroundColor: "var(--hb-angel-card)",
    boxShadow: "var(--hb-angel-shadow-md)",
    color: "var(--hb-color-text-primary)",
    textDecoration: "none",
    transitionProperty: "transform, box-shadow",
    transitionDuration: "var(--hb-angel-dur)",
    transitionTimingFunction: "var(--hb-angel-ease)",
    transform: { default: "none", ":hover": "translateY(-2px)" },
    ":focus-visible": { outline: "none", boxShadow: "var(--hb-angel-focus-ring)" },
  },
  media: {
    position: "relative",
    aspectRatio: "4 / 3.2",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundImage: "repeating-linear-gradient(135deg,#EDE4D6 0 9px,#F5EFE5 9px 18px)",
  },
  mediaLabel: {
    fontFamily: "var(--hb-font-mono)",
    fontSize: "0.65625rem",
    color: "#A79C8B",
  },
  status: {
    position: "absolute",
    top: 11,
    left: 11,
    paddingBlock: 5,
    paddingInline: 11,
    borderRadius: "var(--hb-angel-radius-pill)",
    backgroundColor: "var(--hb-angel-green-tint)",
    color: "var(--hb-color-accent)",
    fontSize: "0.71875rem",
    fontWeight: 600,
  },
  statusReserved: {
    backgroundColor: "var(--hb-angel-warm-tint)",
    color: "#6B4A24",
  },
  favorite: {
    position: "absolute",
    top: 9,
    right: 9,
    width: 31,
    height: 31,
    borderRadius: "50%",
    backgroundColor: "rgba(251,247,240,0.85)",
    color: "var(--hb-color-text-secondary)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  body: { padding: "15px 17px 17px" },
  name: {
    margin: 0,
    fontFamily: "var(--hb-font-body)",
    fontSize: "1rem",
    fontWeight: 600,
    letterSpacing: "-0.01em",
  },
  meta: {
    margin: 0,
    marginTop: 5,
    fontSize: "0.78125rem",
    lineHeight: 1.5,
    color: "var(--hb-color-neutral)",
  },
  where: {
    margin: 0,
    marginTop: 11,
    display: "flex",
    alignItems: "center",
    gap: 5,
    fontSize: "0.75rem",
    color: "#8A9187",
  },
});
