// 보호소 기록지 스타일의 랜딩 히어로 레이아웃과 타이포그래피
import * as stylex from "@stylexjs/stylex";

const TABLET = "@media (min-width: 640px)";
const DESKTOP = "@media (min-width: 960px)";
const REDUCE = "@media (prefers-reduced-motion: reduce)";

const floatUp = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(10px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

export const styles = stylex.create({
  section: {
    backgroundColor: "var(--hb-color-bg)",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--hb-color-text-primary)",
    paddingBlock: { default: "28px 64px", [DESKTOP]: "40px 88px" },
    paddingInline: "clamp(16px, 5vw, 64px)",
  },
  inner: { maxWidth: 1200, marginInline: "auto" },
  meta: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
    paddingBlock: 10,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--hb-color-text-primary)",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--hb-color-text-primary)",
    fontFamily: "var(--hb-font-mono, ui-monospace, monospace)",
    fontSize: "0.6875rem",
    fontWeight: 700,
    letterSpacing: "0.08em",
    color: "var(--hb-color-text-primary)",
  },
  heroGrid: {
    display: "grid",
    gridTemplateColumns: { default: "1fr", [DESKTOP]: "1.35fr 0.85fr" },
    alignItems: "end",
    gap: { default: 48, [DESKTOP]: 64 },
    paddingTop: { default: 40, [DESKTOP]: 58 },
  },
  copy: {
    animationName: floatUp,
    animationDuration: "var(--hb-angel-dur-slow)",
    animationTimingFunction: "var(--hb-angel-ease)",
    animationFillMode: "both",
    [REDUCE]: { animationName: "none" },
  },
  title: {
    margin: 0,
    maxWidth: 760,
    fontSize: { default: "3.2rem", [TABLET]: "4.75rem", [DESKTOP]: "5.75rem" },
    lineHeight: 0.98,
    fontWeight: 900,
    letterSpacing: "-0.065em",
    color: "var(--hb-color-text-primary)",
  },
  titleAccent: { color: "var(--hb-angel-urgent)" },
  lead: {
    margin: 0,
    marginTop: 36,
    maxWidth: 560,
    paddingLeft: 18,
    borderLeftWidth: 3,
    borderLeftStyle: "solid",
    borderLeftColor: "var(--hb-angel-urgent)",
    fontSize: "1rem",
    lineHeight: 1.75,
    color: "var(--hb-color-text-primary)",
  },
  cta: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 34,
  },
  visual: {
    width: "100%",
    margin: 0,
    justifySelf: { default: "center", [DESKTOP]: "end" },
    animationName: floatUp,
    animationDuration: "var(--hb-angel-dur-slow)",
    animationTimingFunction: "var(--hb-angel-ease)",
    animationDelay: "70ms",
    animationFillMode: "both",
    [REDUCE]: { animationName: "none" },
  },
  photoFrame: {
    position: "relative",
    overflow: "hidden",
    aspectRatio: { default: "4 / 3", [DESKTOP]: "4 / 5" },
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-text-primary)",
    backgroundColor: "var(--hb-color-surface)",
  },
  photo: {
    display: "block",
    width: "100%",
    height: "100%",
    objectFit: "cover",
    objectPosition: { default: "center", [DESKTOP]: "64% center" },
    filter: "saturate(0.72) contrast(1.04)",
  },
  countBlock: {
    position: "absolute",
    left: 0,
    bottom: 0,
    width: { default: 104, [TABLET]: 124 },
    height: { default: 104, [TABLET]: 124 },
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "var(--hb-angel-urgent)",
    color: "var(--hb-color-surface)",
    textAlign: "center",
  },
  countValue: {
    fontFamily: "var(--hb-font-mono, ui-monospace, monospace)",
    fontSize: { default: "2rem", [TABLET]: "2.5rem" },
    fontWeight: 900,
    lineHeight: 1,
    fontVariantNumeric: "tabular-nums",
  },
  countLabel: { marginTop: 7, fontSize: "0.6875rem", fontWeight: 700 },
  caption: {
    display: "flex",
    justifyContent: "flex-end",
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--hb-color-text-primary)",
    fontFamily: "var(--hb-font-mono, ui-monospace, monospace)",
    fontSize: "0.625rem",
    letterSpacing: "0.04em",
    color: "var(--hb-color-text-secondary)",
  },
});
