import * as stylex from "@stylexjs/stylex";

const DESKTOP = "@media (min-width: 768px)";
const REDUCE = "@media (prefers-reduced-motion: reduce)";

// Card lifts in on first paint; stilled under reduced-motion.
const fadeUp = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(16px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

export const styles = stylex.create({
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "clamp(16px, 4vw, 40px)",
    backgroundColor: "var(--hb-color-canvas)",
  },
  card: {
    width: "100%",
    maxWidth: 1000,
    display: "grid",
    gridTemplateColumns: { default: "1fr", [DESKTOP]: "1fr 1fr" },
    backgroundColor: "var(--hb-color-surface)",
    borderRadius: 28,
    overflow: "hidden",
    boxShadow: "var(--hb-angel-shadow-lg)",
    animationName: fadeUp,
    animationDuration: "var(--hb-angel-dur-slow)",
    animationTimingFunction: "var(--hb-angel-ease)",
    animationFillMode: "both",
    [REDUCE]: { animationName: "none" },
  },

  // ── Brand panel — photo-first hero (desktop only) ───────
  brand: {
    display: { default: "none", [DESKTOP]: "flex" },
    position: "relative",
    overflow: "hidden",
    flexDirection: "column",
    justifyContent: "space-between",
    gap: 30,
    padding: 48,
    color: "#F2F7F2",
    backgroundImage: "linear-gradient(155deg,#2E6B4E,#1B4433)",
  },
  brandPhoto: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  brandPhotoFrame: {
    height: 230,
    overflow: "hidden",
    borderRadius: 22,
    backgroundColor: "rgba(242,247,242,0.10)",
  },
  brandScrim: { display: "none" },
  brandLogo: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontFamily: "var(--hb-font-display)",
    fontWeight: 700,
    fontSize: "1.1875rem",
  },
  brandLogoIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 30,
    height: 30,
    borderRadius: 11,
    backgroundColor: "rgba(242,247,242,0.18)",
  },
  brandKicker: { display: "none" },
  brandKickerDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    backgroundColor: "var(--hb-angel-accent-warm)",
  },
  brandTitle: {
    position: "relative",
    margin: 0,
    marginTop: 14,
    maxWidth: "24rem",
    fontFamily: "var(--hb-font-display)",
    fontSize: "1.9375rem",
    fontWeight: 700,
    lineHeight: 1.22,
    letterSpacing: "-0.01em",
    textWrap: "balance",
  },
  brandLead: {
    position: "relative",
    margin: 0,
    marginTop: 12,
    maxWidth: "24rem",
    fontSize: "0.90625rem",
    lineHeight: 1.8,
    color: "rgba(242,247,242,0.78)",
  },
  // Floating proof chip overlaid on the photo hero.
  proofChip: { display: "none" },
  proofValue: {
    fontSize: "1.375rem",
    fontWeight: 800,
    fontVariantNumeric: "tabular-nums",
    color: "var(--hb-color-accent-dark)",
  },
  proofLabel: { fontSize: "0.75rem", color: "var(--hb-color-text-secondary)" },

  // ── Form panel ──────────────────────────────────────────
  form: {
    paddingBlock: { default: 36, [DESKTOP]: 48 },
    paddingInline: { default: 24, [DESKTOP]: 48 },
    display: "flex",
    flexDirection: "column",
  },
  overline: {
    display: "inline-flex",
    alignItems: "center",
    fontSize: "0.6875rem",
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "var(--hb-color-accent-dark)",
    marginBottom: 10,
  },
  title: {
    margin: 0,
    fontFamily: "var(--hb-font-display)",
    fontSize: "1.625rem",
    fontWeight: 700,
    letterSpacing: "-0.015em",
    color: "var(--hb-color-text-primary)",
  },
  subtitle: {
    margin: 0,
    marginTop: 8,
    marginBottom: 28,
    fontSize: "0.875rem",
    lineHeight: 1.6,
    color: "var(--hb-color-text-secondary)",
  },
  fields: { display: "flex", flexDirection: "column", gap: 16 },
  pwLabelRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  labelText: { fontSize: "0.875rem", fontWeight: 600, color: "var(--hb-color-text-primary)" },
  link: { fontSize: "0.8125rem", fontWeight: 600, color: "var(--hb-color-accent-dark)" },
  toggle: {
    minHeight: 40,
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    fontSize: "0.8125rem",
    color: "var(--hb-color-text-secondary)",
    paddingInline: 8,
  },
  remember: {
    marginTop: 18,
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 40,
    fontSize: "0.875rem",
    color: "var(--hb-color-text-secondary)",
    cursor: "pointer",
  },
  submit: { marginTop: 20 },
  divider: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBlock: 22,
    color: "var(--hb-color-text-secondary)",
    fontSize: "0.8125rem",
  },
  dividerLine: { flex: 1, height: 1, backgroundColor: "var(--hb-color-border)" },
  signup: { textAlign: "center", fontSize: "0.875rem", color: "var(--hb-color-text-secondary)" },
  signupLink: { fontWeight: 700, color: "var(--hb-color-accent-dark)" },
});
