import * as stylex from "@stylexjs/stylex";

const DESKTOP = "@media (min-width: 768px)";
const REDUCE = "@media (prefers-reduced-motion: reduce)";

// Card lifts in on first paint; stilled under reduced-motion.
const fadeUp = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(16px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

export const styles = stylex.create({
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "clamp(16px, 4vw, 40px)",
    backgroundImage: "var(--hb-angel-hero-wash)",
  },
  card: {
    width: "100%",
    maxWidth: 960,
    display: "grid",
    gridTemplateColumns: { default: "1fr", [DESKTOP]: "0.95fr 1.05fr" },
    backgroundColor: "var(--hb-color-surface)",
    borderRadius: "var(--hb-angel-radius-card)",
    overflow: "hidden",
    boxShadow: "var(--hb-angel-shadow-lg)",
    animationName: fadeUp,
    animationDuration: "var(--hb-angel-dur-slow)",
    animationTimingFunction: "var(--hb-angel-ease)",
    animationFillMode: "both",
    [REDUCE]: { animationName: "none" },
  },

  // ── Brand panel — photo-first hero (desktop only) ───────
  brand: {
    display: { default: "none", [DESKTOP]: "flex" },
    position: "relative",
    overflow: "hidden",
    flexDirection: "column",
    justifyContent: "space-between",
    gap: 24,
    padding: 40,
    color: "var(--hb-angel-on-photo)",
    // Graceful fallback: if the hero asset fails to load, brand copy still sits
    // on a legible branded surface rather than a bare white panel.
    backgroundColor: "var(--hb-angel-green-deep)",
    isolation: "isolate",
  },
  brandPhoto: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    zIndex: -2,
  },
  brandScrim: {
    position: "absolute",
    inset: 0,
    zIndex: -1,
    backgroundImage: "var(--hb-angel-photo-scrim-brand)",
  },
  brandLogo: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontWeight: 700,
    fontSize: "1.0625rem",
  },
  brandLogoIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: "var(--hb-angel-on-photo-fill)",
    fontSize: "0.95rem",
  },
  brandKicker: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontSize: "0.6875rem",
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "var(--hb-angel-on-photo-strong)",
  },
  brandKickerDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    backgroundColor: "var(--hb-angel-accent-warm)",
  },
  brandTitle: {
    position: "relative",
    margin: 0,
    marginTop: 14,
    fontSize: "1.75rem",
    fontWeight: 700,
    lineHeight: 1.22,
    letterSpacing: "-0.02em",
  },
  brandLead: {
    position: "relative",
    margin: 0,
    marginTop: 12,
    fontSize: "0.9375rem",
    lineHeight: 1.6,
    color: "var(--hb-angel-on-photo-muted)",
  },
  // Floating proof chip overlaid on the photo hero.
  proofChip: {
    position: "relative",
    alignSelf: "flex-start",
    display: "flex",
    flexDirection: "column",
    gap: 2,
    paddingBlock: 12,
    paddingInline: 16,
    borderRadius: "var(--hb-angel-radius-md)",
    backgroundColor: "var(--hb-color-surface)",
    boxShadow: "var(--hb-angel-shadow-lg)",
  },
  proofValue: {
    fontSize: "1.375rem",
    fontWeight: 800,
    fontVariantNumeric: "tabular-nums",
    color: "var(--hb-color-accent-dark)",
  },
  proofLabel: { fontSize: "0.75rem", color: "var(--hb-color-text-secondary)" },

  // ── Form panel ──────────────────────────────────────────
  form: {
    paddingBlock: { default: 36, [DESKTOP]: 48 },
    paddingInline: { default: 24, [DESKTOP]: 48 },
    display: "flex",
    flexDirection: "column",
  },
  overline: {
    display: "inline-flex",
    alignItems: "center",
    fontSize: "0.6875rem",
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "var(--hb-color-accent-dark)",
    marginBottom: 10,
  },
  title: {
    position: "relative",
    margin: 0,
    paddingLeft: 16,
    fontSize: "1.625rem",
    fontWeight: 700,
    letterSpacing: "-0.015em",
    color: "var(--hb-color-text-primary)",
    "::before": {
      content: "''",
      position: "absolute",
      left: 0,
      top: "0.15em",
      width: 3,
      height: "1.1em",
      borderRadius: 999,
      backgroundColor: "var(--hb-color-accent)",
    },
  },
  subtitle: {
    margin: 0,
    marginTop: 8,
    marginBottom: 28,
    paddingLeft: 16,
    fontSize: "1.0625rem",
    lineHeight: 1.6,
    color: "var(--hb-color-text-secondary)",
  },
  fields: { display: "flex", flexDirection: "column", gap: 16 },
  pwLabelRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  labelText: { fontSize: "0.875rem", fontWeight: 600, color: "var(--hb-color-text-primary)" },
  link: { fontSize: "0.8125rem", fontWeight: 600, color: "var(--hb-color-accent-dark)" },
  toggle: {
    minHeight: 40,
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    fontSize: "0.8125rem",
    color: "var(--hb-color-text-secondary)",
    paddingInline: 8,
  },
  remember: {
    marginTop: 18,
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 40,
    fontSize: "0.875rem",
    color: "var(--hb-color-text-secondary)",
    cursor: "pointer",
  },
  submit: { marginTop: 20 },
  divider: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBlock: 22,
    color: "var(--hb-color-text-secondary)",
    fontSize: "0.8125rem",
  },
  dividerLine: { flex: 1, height: 1, backgroundColor: "var(--hb-color-border)" },
  signup: { textAlign: "center", fontSize: "0.875rem", color: "var(--hb-color-text-secondary)" },
  signupLink: { fontWeight: 700, color: "var(--hb-color-accent-dark)" },
});
