import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  body: {
    display: "flex",
    flexDirection: "column",
    gap: 18,
    minWidth: { default: "auto", "@media (min-width: 640px)": 440 },
  },
  titleRow: { display: "flex", alignItems: "center", gap: 10 },
  shelterName: {
    margin: 0,
    fontSize: "1.125rem",
    fontWeight: 700,
    color: "var(--hb-color-text-primary)",
  },
  section: { display: "flex", flexDirection: "column", gap: 8 },
  sectionLabel: {
    fontSize: "0.6875rem",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--hb-color-text-secondary)",
  },
  // Grouped dossier fields sit on a soft surface-alt panel (no hairline border).
  panel: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 14,
    borderRadius: "var(--hb-angel-radius-md)",
    backgroundColor: "var(--hb-angel-surface-alt)",
  },
  rows: { display: "flex", flexDirection: "column", gap: 6 },
  row: { display: "flex", gap: 10, fontSize: "0.875rem" },
  rowKey: { flexShrink: 0, minWidth: 88, color: "var(--hb-color-text-secondary)" },
  rowValue: { color: "var(--hb-color-text-primary)", fontWeight: 500 },
  mono: { fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace" },
  signals: { display: "flex", flexDirection: "row", flexWrap: "wrap", gap: 8 },
  signal: { display: "flex", alignItems: "center", gap: 6 },
  signalKey: { fontSize: "0.8125rem", color: "var(--hb-color-text-primary)" },
  muted: { fontSize: "0.875rem", color: "var(--hb-color-text-secondary)" },
  photos: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(96px, 1fr))",
    gap: 8,
  },
  photo: {
    position: "relative",
    aspectRatio: "1 / 1",
    borderRadius: "var(--hb-angel-radius-sm)",
    overflow: "hidden",
    backgroundColor: "var(--hb-angel-surface-alt)",
  },
  photoImg: { width: "100%", height: "100%", objectFit: "cover" },
  photoKind: {
    position: "absolute",
    left: 6,
    bottom: 6,
    paddingBlock: 2,
    paddingInline: 6,
    borderRadius: 6,
    fontSize: "0.6875rem",
    fontWeight: 600,
    color: "var(--hb-angel-on-photo)",
    backgroundColor: "var(--hb-angel-disc-scrim-strong)",
  },
  rejection: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: 12,
    borderRadius: "var(--hb-angel-radius-sm)",
    backgroundColor: "var(--hb-angel-urgent-tint)",
  },
});
