import * as stylex from "@stylexjs/stylex";

const WIDE = "@media (min-width: 1024px)";
const REDUCE = "@media (prefers-reduced-motion: reduce)";

export const styles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    height: { [WIDE]: "100%" },
    minHeight: 0,
  },
  // Full-width body split 1:1 — form on the left, the list on the right; each
  // column scrolls on its own.
  layout: {
    display: "grid",
    gridTemplateColumns: { default: "1fr", [WIDE]: "1fr 1fr" },
    alignItems: "start",
    gap: 20,
    flex: { [WIDE]: 1 },
    minHeight: 0,
  },
  col: {
    minHeight: 0,
    height: { [WIDE]: "100%" },
    overflowY: { [WIDE]: "auto" },
  },
  // ── Header: overline kicker + accent left-rule + title + warm-muted subtitle ──
  header: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    paddingLeft: 14,
    borderLeftWidth: 3,
    borderLeftStyle: "solid",
    borderLeftColor: "var(--hb-color-accent)",
  },
  kicker: {
    fontSize: "0.6875rem",
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "var(--hb-color-accent-dark)",
  },
  title: {
    margin: 0,
    fontSize: "1.5rem",
    fontWeight: 700,
    letterSpacing: "-0.015em",
    color: "var(--hb-color-text-primary)",
  },
  subtitle: {
    margin: 0,
    fontSize: "0.9375rem",
    color: "var(--hb-color-text-secondary)",
  },
  subtabs: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginBlock: 18,
  },
  tab: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: 40,
    padding: "8px 16px",
    borderRadius: "var(--hb-angel-radius-pill)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-angel-surface-alt)",
    fontSize: "0.875rem",
    fontWeight: 600,
    fontFamily: "inherit",
    color: "var(--hb-color-text-secondary)",
    backgroundColor: "var(--hb-color-surface)",
    cursor: "pointer",
    transitionProperty: "color, background-color, border-color",
    transitionDuration: "var(--hb-angel-dur)",
    transitionTimingFunction: "var(--hb-angel-ease)",
    [REDUCE]: { transitionDuration: "0ms" },
  },
  tabActive: {
    color: "var(--hb-color-accent-dark)",
    borderColor: "var(--hb-color-accent)",
    backgroundColor: "var(--hb-angel-green-tint)",
  },
  tabSoon: {
    color: "var(--hb-color-text-secondary)",
    borderColor: "var(--hb-angel-surface-alt)",
    backgroundColor: "var(--hb-angel-surface-alt)",
    cursor: "default",
  },
  // Form + list stacked. Soft float instead of a flat 1px border.
  card: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: 20,
    borderRadius: "var(--hb-angel-radius-card)",
    backgroundColor: "var(--hb-color-surface)",
    boxShadow: "var(--hb-angel-shadow-sm)",
  },
  // ── Form section heading: overline kicker + title ──
  headingGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  headingKicker: {
    fontSize: "0.6875rem",
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "var(--hb-color-accent-dark)",
  },
  heading: {
    margin: 0,
    fontSize: "1rem",
    fontWeight: 700,
    letterSpacing: "-0.01em",
    color: "var(--hb-color-text-primary)",
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    padding: "10px 12px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "transparent",
    borderRadius: "var(--hb-angel-radius-control)",
    fontSize: "0.9375rem",
    fontFamily: "inherit",
    color: "var(--hb-color-text-primary)",
    backgroundColor: "var(--hb-angel-surface-alt)",
    outline: "none",
    transitionProperty: "border-color, box-shadow",
    transitionDuration: "var(--hb-angel-dur)",
    transitionTimingFunction: "var(--hb-angel-ease)",
    [REDUCE]: { transitionDuration: "0ms" },
  },
  inputFocus: {
    borderColor: {
      default: "transparent",
      ":focus-visible": "var(--hb-color-accent)",
    },
    boxShadow: {
      default: null,
      ":focus-visible": "var(--hb-angel-focus-ring)",
    },
  },
  textarea: {
    minHeight: 96,
    resize: "vertical",
  },
  check: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: "0.9375rem",
    color: "var(--hb-color-text-primary)",
    cursor: "pointer",
  },
  actions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  // ── Empty state: branded green-tint tile with a kicker, not bare dashed grey ──
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
    padding: { default: "28px 20px", [WIDE]: "36px 20px" },
    textAlign: "center",
    borderRadius: "var(--hb-angel-radius-card)",
    backgroundColor: "var(--hb-angel-green-tint)",
  },
  emptyKicker: {
    fontSize: "0.6875rem",
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "var(--hb-color-accent-dark)",
  },
  emptyText: {
    margin: 0,
    color: "var(--hb-color-text-secondary)",
    fontSize: "0.9375rem",
  },
  row: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 16,
    borderRadius: "var(--hb-angel-radius-md)",
    backgroundColor: "var(--hb-color-surface)",
    boxShadow: "var(--hb-angel-shadow-sm)",
    transitionProperty: "background-color, box-shadow",
    transitionDuration: "var(--hb-angel-dur)",
    transitionTimingFunction: "var(--hb-angel-ease)",
    [REDUCE]: { transitionDuration: "0ms" },
    ":hover": { backgroundColor: "var(--hb-angel-surface-alt)" },
  },
  rowActive: {
    backgroundColor: "var(--hb-angel-green-tint)",
    boxShadow: "0 0 0 1px var(--hb-color-accent), var(--hb-angel-shadow-sm)",
    ":hover": { backgroundColor: "var(--hb-angel-green-tint)" },
  },
  rowHead: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  rowTitle: {
    fontSize: "0.9375rem",
    fontWeight: 700,
    letterSpacing: "-0.01em",
    color: "var(--hb-color-text-primary)",
  },
  preview: {
    margin: 0,
    fontSize: "0.875rem",
    color: "var(--hb-color-text-secondary)",
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
  },
  rowActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 4,
  },
  spacer: {
    flex: 1,
  },
});
