import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: 20,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    borderRadius: "var(--hb-angel-radius-card)",
    backgroundColor: "var(--hb-color-surface)",
  },
  nameRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  name: {
    margin: 0,
    fontSize: "1.5rem",
    fontWeight: 800,
    color: "var(--hb-color-text-primary)",
  },
  meta: {
    margin: 0,
    fontSize: "0.9375rem",
    color: "var(--hb-color-text-secondary)",
  },
  badges: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  badge: {
    paddingBlock: 5,
    paddingInline: 10,
    borderRadius: 999,
    backgroundColor: "var(--hb-angel-green-tint)",
    color: "var(--hb-color-accent-dark)",
    fontSize: "0.75rem",
    fontWeight: 600,
  },
  ctas: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginTop: 4,
  },
  secondaryRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  iconAction: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    height: 40,
    paddingInline: 14,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    borderRadius: "var(--hb-radius-control, 8px)",
    backgroundColor: "transparent",
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "var(--hb-color-text-secondary)",
    cursor: "pointer",
  },
  bookmarkOn: {
    borderColor: "var(--hb-color-accent)",
    color: "var(--hb-color-accent-dark)",
    backgroundColor: "var(--hb-angel-green-tint)",
  },
  inquiry: {
    marginTop: 4,
    paddingBlock: 8,
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "var(--hb-color-accent-dark)",
    cursor: "pointer",
    textAlign: "left",
  },
});
