import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: 20,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    borderRadius: "var(--hb-angel-radius-card)",
    backgroundColor: "var(--hb-color-surface)",
  },
  nameRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  name: {
    margin: 0,
    fontSize: "1.5rem",
    fontWeight: 800,
    color: "var(--hb-color-text-primary)",
  },
  meta: {
    margin: 0,
    fontSize: "0.9375rem",
    color: "var(--hb-color-text-secondary)",
  },
  badges: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  badge: {
    paddingBlock: 5,
    paddingInline: 10,
    borderRadius: 999,
    backgroundColor: "var(--hb-angel-green-tint)",
    color: "var(--hb-color-accent-dark)",
    fontSize: "0.75rem",
    fontWeight: 600,
  },
  // ♡ bookmark — a light affordance in the top-right of the name row.
  bookmark: {
    marginInlineStart: "auto",
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 34,
    height: 34,
    borderRadius: 999,
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: { default: "transparent", ":hover": "var(--hb-color-canvas)" },
    color: "var(--hb-color-text-secondary)",
    cursor: "pointer",
  },
  bookmarkOn: {
    color: "var(--hb-color-accent-dark)",
  },
  ctas: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginTop: 16,
  },
  // Tertiary action — quiet text link centered under the buttons.
  inquiry: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    paddingTop: 8,
    paddingBottom: 0,
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "var(--hb-color-text-secondary)",
    cursor: "pointer",
  },

  // Owning-shelter shortcut (§02). Links to the shelter microsite by slug.
  shelter: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    paddingBlock: 10,
    paddingInline: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    borderRadius: 12,
    backgroundColor: "var(--hb-color-surface)",
    color: "var(--hb-color-text-primary)",
    textDecoration: "none",
  },
  shelterPin: {
    flexShrink: 0,
    color: "var(--hb-color-accent-dark)",
  },
  shelterInfo: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    minWidth: 0,
    flex: 1,
  },
  shelterName: {
    fontSize: "0.9375rem",
    fontWeight: 700,
    color: "var(--hb-color-text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  shelterLoc: {
    fontSize: "0.8125rem",
    color: "var(--hb-color-text-secondary)",
  },
  shelterChevron: {
    flexShrink: 0,
    color: "var(--hb-color-text-secondary)",
  },
});
