import * as stylex from "@stylexjs/stylex";

const WIDE = "@media (min-width: 1024px)";

export const styles = stylex.create({
  // The console main is a fixed pane; this screen owns its own vertical scroll.
  root: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    height: { [WIDE]: "100%" },
    minHeight: 0,
  },
  title: {
    margin: 0,
    fontSize: "1.5rem",
    fontWeight: 700,
    color: "var(--hb-color-text-primary)",
  },
  subtitle: {
    margin: "4px 0 16px",
    fontSize: "0.9375rem",
    color: "var(--hb-color-text-secondary)",
  },
  purposeTabs: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 14,
  },
  tab: {
    padding: "7px 14px",
    borderRadius: 999,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    fontSize: "0.875rem",
    fontWeight: 600,
    fontFamily: "inherit",
    color: "var(--hb-color-text-secondary)",
    backgroundColor: "var(--hb-color-surface)",
    cursor: "pointer",
  },
  tabActive: {
    color: "var(--hb-color-accent-dark, oklch(0.46 0.08 155))",
    borderColor: "oklch(0.86 0.06 155)",
    backgroundColor: "oklch(0.93 0.045 155)",
  },
  builder: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    flex: { [WIDE]: 1 },
  },
  // Publish bar: version state on the left, draft/publish actions on the right.
  topBar: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 10,
    paddingBottom: 12,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--hb-color-border)",
  },
  // A quiet save-status cluster: a state dot, the version, and a plain caption.
  status: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    flexShrink: 0,
  },
  statusDotSaved: {
    backgroundColor: "var(--hb-color-accent)",
  },
  statusDotDraft: {
    backgroundColor: "var(--hb-color-warning, oklch(0.75 0.15 75))",
  },
  statusVersion: {
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "var(--hb-color-text-primary)",
  },
  statusCaption: {
    fontSize: "0.8125rem",
    color: "var(--hb-color-text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  topSpacer: {
    flex: 1,
  },
  // Builder on the left, live applicant preview on the right.
  panes: {
    display: "grid",
    gridTemplateColumns: { default: "1fr", [WIDE]: "1fr 1fr" },
    gap: 16,
    minHeight: 0,
    flex: { [WIDE]: 1 },
  },
  pane: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    minHeight: 0,
    overflowY: { [WIDE]: "auto" },
  },
  paneHeading: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    margin: 0,
    fontSize: "0.9375rem",
    fontWeight: 700,
    color: "var(--hb-color-text-primary)",
  },
  paneCount: {
    fontSize: "0.8125rem",
    fontWeight: 500,
    color: "var(--hb-color-text-secondary)",
  },
  // Field list.
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  fieldRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    backgroundColor: { default: "var(--hb-color-surface)", ":hover": "var(--hb-color-canvas)" },
    textAlign: "start",
    fontFamily: "inherit",
    cursor: "pointer",
    width: "100%",
    boxSizing: "border-box",
  },
  fieldRowActive: {
    borderColor: "var(--hb-color-accent)",
    backgroundColor: "oklch(0.97 0.02 155)",
  },
  fieldRowInvalid: {
    borderColor: "var(--hb-color-danger, oklch(0.55 0.18 25))",
  },
  handle: {
    fontSize: "1rem",
    color: "var(--hb-color-text-disabled)",
    lineHeight: 1,
  },
  fieldText: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
    flex: 1,
  },
  fieldTitle: {
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "var(--hb-color-text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fieldTitlePlaceholder: {
    color: "var(--hb-color-text-disabled)",
    fontWeight: 500,
  },
  fieldMeta: {
    fontFamily: "var(--hb-font-mono, ui-monospace, monospace)",
    fontSize: "0.6875rem",
    color: "var(--hb-color-text-secondary)",
  },
  emptyList: {
    padding: "24px 12px",
    textAlign: "center",
    color: "var(--hb-color-text-secondary)",
    fontSize: "0.875rem",
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "var(--hb-color-border)",
  },
  // Palette of field types to add.
  palette: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
    paddingTop: 4,
  },
  paletteLabel: {
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "var(--hb-color-text-secondary)",
    marginRight: 2,
  },
  chip: {
    padding: "5px 11px",
    borderRadius: 999,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    fontSize: "0.8125rem",
    fontFamily: "inherit",
    fontWeight: 500,
    color: "var(--hb-color-text-primary)",
    backgroundColor: { default: "var(--hb-color-surface)", ":hover": "oklch(0.95 0.03 155)" },
    cursor: "pointer",
  },
  // Selected-field editor.
  editor: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    backgroundColor: "var(--hb-color-surface-subtle)",
  },
  editorTitle: {
    margin: 0,
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "var(--hb-color-text-primary)",
  },
  editorHint: {
    padding: "24px 12px",
    textAlign: "center",
    fontSize: "0.875rem",
    color: "var(--hb-color-text-secondary)",
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "var(--hb-color-border)",
  },
  label: {
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "var(--hb-color-text-secondary)",
  },
  check: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: "0.875rem",
    color: "var(--hb-color-text-primary)",
    cursor: "pointer",
  },
  options: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  optionRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  optionInput: {
    flex: 1,
  },
  error: {
    fontSize: "0.75rem",
    color: "var(--hb-color-danger, oklch(0.55 0.18 25))",
  },
  // Preview pane — the applicant's view.
  preview: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    backgroundColor: "var(--hb-color-surface-subtle)",
  },
  previewEmpty: {
    fontSize: "0.875rem",
    color: "var(--hb-color-text-secondary)",
  },
  // The preview mirrors the applicant funnel but isn't answerable here.
  previewLock: {
    pointerEvents: "none",
    userSelect: "none",
  },
});
