import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  card: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    padding: 20,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    backgroundColor: "var(--hb-color-surface)",
  },
  headingRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  heading: {
    margin: 0,
    fontSize: "1rem",
    fontWeight: 700,
    color: "var(--hb-color-text-primary)",
  },
  spacer: {
    flex: 1,
  },
  linkBtn: {
    padding: 0,
    borderWidth: 0,
    background: "none",
    fontSize: "0.8125rem",
    fontWeight: 600,
    color: "var(--hb-color-accent-dark, var(--hb-color-accent))",
    cursor: "pointer",
  },
  attach: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  thumb: {
    position: "relative",
    width: 64,
    height: 64,
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
  },
  thumbImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  thumbRemove: {
    position: "absolute",
    insetBlockStart: 2,
    insetInlineEnd: 2,
    width: 20,
    height: 20,
    padding: 0,
    borderWidth: 0,
    borderRadius: 999,
    color: "#fff",
    fontSize: "0.75rem",
    lineHeight: 1,
    cursor: "pointer",
    backgroundColor: "rgba(0, 0, 0, 0.55)",
  },
  attachBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 64,
    height: 64,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "var(--hb-color-border)",
    fontSize: "0.75rem",
    color: "var(--hb-color-text-secondary)",
    cursor: "pointer",
  },
  hiddenInput: {
    display: "none",
  },
  emptyPhotos: {
    fontSize: "0.8125rem",
    color: "var(--hb-color-text-secondary)",
  },
  note: {
    fontSize: "0.75rem",
    color: "var(--hb-color-text-disabled)",
  },
  actions: {
    display: "flex",
    gap: 8,
  },
});
