// Claude Design 봉사 일정 카드의 정보 순서·모집률·상호작용 스타일
import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  card: {
    display: "flex",
    flexDirection: "column",
    padding: "24px 26px",
    borderRadius: 24,
    backgroundColor: "var(--hb-angel-card)",
    boxShadow: "0 1px 2px rgba(34,49,42,0.05),0 12px 30px -22px rgba(34,49,42,0.30)",
  },
  chips: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  title: {
    margin: 0,
    marginTop: 14,
    fontFamily: "var(--hb-font-body)",
    fontSize: "1.125rem",
    fontWeight: 600,
    letterSpacing: "-0.01em",
    color: "var(--hb-color-text-primary)",
  },
  metaRow: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    marginTop: 10,
    fontSize: "0.8125rem",
    color: "var(--hb-color-text-secondary)",
  },
  shelterLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    marginTop: 8,
    fontSize: "0.78125rem",
    color: "var(--hb-color-neutral)",
    textDecoration: "none",
  },
  description: {
    marginTop: 12,
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    fontFamily: "var(--hb-font-body)",
    fontSize: "0.84375rem",
    lineHeight: 1.7,
    color: "var(--hb-color-neutral)",
    textAlign: "left",
    cursor: "pointer",
  },
  progressBlock: { marginTop: 18, marginBottom: 18 },
  captionRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
    fontSize: "0.78125rem",
    color: "var(--hb-color-neutral)",
  },
  urgent: {
    display: "block",
    marginTop: 6,
    fontSize: "0.71875rem",
    color: "var(--hb-color-danger)",
  },
});
