import * as stylex from "@stylexjs/stylex";

const WIDE = "@media (min-width: 1024px)";

export const styles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    height: { [WIDE]: "100%" },
    minHeight: 0,
  },
  title: {
    margin: 0,
    fontSize: "1.5rem",
    fontWeight: 700,
    color: "var(--hb-color-text-primary)",
  },
  subtitle: {
    margin: "4px 0 16px",
    fontSize: "0.9375rem",
    color: "var(--hb-color-text-secondary)",
  },
  toolbar: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 12,
    marginBottom: 14,
  },
  filters: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  filterChip: {
    padding: "5px 12px",
    borderRadius: 999,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    fontSize: "0.8125rem",
    fontWeight: 600,
    fontFamily: "inherit",
    color: "var(--hb-color-text-secondary)",
    backgroundColor: "var(--hb-color-surface)",
    cursor: "pointer",
  },
  filterChipActive: {
    color: "var(--hb-color-accent-dark, oklch(0.46 0.08 155))",
    borderColor: "oklch(0.86 0.06 155)",
    backgroundColor: "oklch(0.93 0.045 155)",
  },
  layout: {
    display: "grid",
    gridTemplateColumns: { default: "1fr", [WIDE]: "minmax(0, 1fr) minmax(0, 1fr)" },
    alignItems: "start",
    gap: 16,
    flex: { [WIDE]: 1 },
    minHeight: 0,
  },
  col: {
    minHeight: 0,
    height: { [WIDE]: "100%" },
    overflowY: { [WIDE]: "auto" },
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
    boxSizing: "border-box",
    padding: "12px 14px",
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    backgroundColor: { default: "var(--hb-color-surface)", ":hover": "var(--hb-color-canvas)" },
    textAlign: "start",
    fontFamily: "inherit",
    cursor: "pointer",
  },
  rowActive: {
    borderColor: "var(--hb-color-accent)",
    backgroundColor: "oklch(0.97 0.02 155)",
  },
  rowMain: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
    flex: 1,
  },
  rowTitle: {
    fontSize: "0.9375rem",
    fontWeight: 600,
    color: "var(--hb-color-text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowMeta: {
    fontSize: "0.75rem",
    color: "var(--hb-color-text-secondary)",
  },
  empty: {
    padding: "36px 16px",
    textAlign: "center",
    color: "var(--hb-color-text-secondary)",
    fontSize: "0.9375rem",
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "var(--hb-color-border)",
  },
  more: {
    display: "flex",
    justifyContent: "center",
    paddingTop: 4,
  },
  // Detail panel.
  detail: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    backgroundColor: "var(--hb-color-surface)",
  },
  detailHead: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  detailTitle: {
    margin: 0,
    fontSize: "1.125rem",
    fontWeight: 700,
    color: "var(--hb-color-text-primary)",
  },
  detailMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "2px 12px",
    fontSize: "0.8125rem",
    color: "var(--hb-color-text-secondary)",
  },
  answers: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    paddingTop: 4,
  },
  answer: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  answerPrompt: {
    fontSize: "0.8125rem",
    fontWeight: 600,
    color: "var(--hb-color-text-secondary)",
  },
  answerText: {
    fontSize: "0.9375rem",
    color: "var(--hb-color-text-primary)",
    whiteSpace: "pre-line",
  },
  sectionLabel: {
    margin: "4px 0 0",
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "var(--hb-color-text-primary)",
  },
  hint: {
    padding: "48px 16px",
    textAlign: "center",
    color: "var(--hb-color-text-secondary)",
    fontSize: "0.9375rem",
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "var(--hb-color-border)",
  },
});
