import * as stylex from "@stylexjs/stylex";

const WIDE = "@media (min-width: 1024px)";
const NARROW = "@media (max-width: 390px)";
const TINY = "@media (max-width: 360px)";
const REDUCE = "@media (prefers-reduced-motion: reduce)";

export const styles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    height: { [WIDE]: "100%" },
    minHeight: 0,
  },
  // Section header with overline kicker + accent left-rule.
  header: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    marginBottom: 16,
  },
  kicker: {
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    fontSize: "0.6875rem",
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "var(--hb-color-accent-dark)",
  },
  kickerRule: {
    display: "inline-block",
    width: 3,
    height: 24,
    borderRadius: "var(--hb-angel-radius-pill)",
    backgroundColor: "var(--hb-color-accent)",
  },
  title: {
    margin: 0,
    fontSize: "1.5rem",
    fontWeight: 700,
    letterSpacing: "-0.015em",
    color: "var(--hb-color-text-primary)",
  },
  subtitle: {
    margin: 0,
    fontSize: "0.9375rem",
    color: "var(--hb-color-text-secondary)",
  },
  // Sticky toolbar — stays legible over the scrolling list.
  toolbar: {
    position: "sticky",
    top: 0,
    zIndex: 2,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 12,
    marginBottom: 14,
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: "var(--hb-color-surface)",
    boxShadow: "var(--hb-angel-shadow-sm)",
    borderRadius: "var(--hb-angel-radius-md)",
    paddingInline: 12,
  },
  filters: {
    display: "flex",
    flexWrap: "wrap",
    gap: { default: 6, [NARROW]: 4 },
    minWidth: 0,
  },
  filterChip: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: 40,
    padding: "0 14px",
    borderRadius: "var(--hb-angel-radius-pill)",
    borderWidth: 0,
    borderStyle: "none",
    fontSize: "0.8125rem",
    fontWeight: 600,
    fontFamily: "inherit",
    color: "var(--hb-color-text-secondary)",
    backgroundColor: {
      default: "var(--hb-angel-surface-alt)",
      ":hover": "var(--hb-angel-green-tint)",
    },
    cursor: "pointer",
    transitionProperty: "background-color, color, box-shadow",
    transitionDuration: "var(--hb-angel-dur)",
    transitionTimingFunction: "var(--hb-angel-ease)",
    outline: { ":focus-visible": "none" },
    boxShadow: { ":focus-visible": "var(--hb-angel-focus-ring)" },
    [REDUCE]: { transitionProperty: "none" },
  },
  filterChipActive: {
    color: "var(--hb-color-accent-dark)",
    backgroundColor: "var(--hb-angel-green-tint)",
    boxShadow: {
      default: "inset 0 0 0 1px var(--hb-color-accent)",
      ":focus-visible": "var(--hb-angel-focus-ring)",
    },
  },
  layout: {
    display: "grid",
    gridTemplateColumns: { default: "1fr", [WIDE]: "minmax(0, 1fr) minmax(0, 1fr)" },
    alignItems: "start",
    gap: 16,
    flex: { [WIDE]: 1 },
    minHeight: 0,
  },
  col: {
    minHeight: 0,
    height: { [WIDE]: "100%" },
    overflowY: { [WIDE]: "auto" },
    // `overflow-y: auto` computes overflow-x to auto as well, so this column is a
    // scroll container that clips at its edges — shaving the cards' hover shadow
    // and selected ring. Pad the scroll box, then pull the padding back out so
    // the cards stay exactly where they were.
    padding: { default: 0, [WIDE]: 8 },
    margin: { default: 0, [WIDE]: -8 },
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  // Soft-float row card (no flat border).
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
    boxSizing: "border-box",
    padding: "12px 14px",
    borderRadius: "var(--hb-angel-radius-md)",
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "var(--hb-color-surface)",
    boxShadow: {
      default: "var(--hb-angel-shadow-sm)",
      ":hover": "var(--hb-angel-shadow-md)",
    },
    textAlign: "start",
    fontFamily: "inherit",
    cursor: "pointer",
    transitionProperty: "box-shadow, transform",
    transitionDuration: "var(--hb-angel-dur)",
    transitionTimingFunction: "var(--hb-angel-ease)",
    transform: { default: "none", ":hover": "translateY(-2px)" },
    outline: { ":focus-visible": "none" },
    [REDUCE]: { transitionProperty: "none", transform: "none" },
  },
  rowActive: {
    backgroundColor: "var(--hb-angel-green-tint)",
    boxShadow: "inset 0 0 0 1.5px var(--hb-color-accent), var(--hb-angel-shadow-sm)",
  },
  rowMain: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
    flex: 1,
  },
  rowTitle: {
    fontSize: "0.9375rem",
    fontWeight: 600,
    color: "var(--hb-color-text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowMeta: {
    fontSize: "0.75rem",
    color: "var(--hb-color-text-secondary)",
  },
  // Branded calm empty tile (no dashed grey).
  empty: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "clamp(28px, 6vw, 36px) 16px",
    textAlign: "center",
    color: "var(--hb-color-accent-dark)",
    fontSize: "0.9375rem",
    fontWeight: 600,
    borderRadius: "var(--hb-angel-radius-card)",
    backgroundColor: "var(--hb-angel-green-tint)",
  },
  more: {
    display: "flex",
    justifyContent: "center",
    paddingTop: 4,
  },
  // Detail panel — the focused work surface, floats.
  detail: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    padding: 20,
    borderRadius: "var(--hb-angel-radius-card)",
    backgroundColor: "var(--hb-color-surface)",
    boxShadow: "var(--hb-angel-shadow-md)",
  },
  detailHead: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  detailHeadRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  detailTitle: {
    margin: 0,
    fontSize: "1.125rem",
    fontWeight: 700,
    letterSpacing: "-0.015em",
    color: "var(--hb-color-text-primary)",
  },
  detailMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "2px 12px",
    fontSize: "0.8125rem",
    color: "var(--hb-color-text-secondary)",
  },
  answers: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    paddingTop: 4,
  },
  answer: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  answerPrompt: {
    fontSize: "0.8125rem",
    fontWeight: 600,
    color: "var(--hb-color-text-secondary)",
  },
  answerText: {
    fontSize: "0.9375rem",
    color: "var(--hb-color-text-primary)",
    whiteSpace: "pre-line",
  },
  sectionLabel: {
    margin: "4px 0 0",
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "var(--hb-color-text-primary)",
  },
  // Branded hint tile (no dashed grey).
  hint: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: "clamp(32px, 7vw, 48px) 16px",
    textAlign: "center",
    color: "var(--hb-color-text-secondary)",
    fontSize: "0.9375rem",
    borderRadius: "var(--hb-angel-radius-card)",
    backgroundColor: "var(--hb-angel-surface-alt)",
  },
  hintText: {
    margin: 0,
    maxWidth: "26rem",
  },
  // Approve / reject side-by-side (each fills its cell); stacks below ~360px.
  decisionBar: {
    display: "grid",
    gridTemplateColumns: { default: "1fr 1fr", [TINY]: "1fr" },
    gap: 8,
    marginTop: 4,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--hb-color-border)",
  },
  // Rejection reads as attention (urgent), not warm.
  rejectReason: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: "12px 12px 12px 14px",
    borderRadius: "var(--hb-angel-radius-sm)",
    borderLeftWidth: 3,
    borderLeftStyle: "solid",
    borderLeftColor: "var(--hb-angel-urgent)",
    backgroundColor: "var(--hb-angel-urgent-tint)",
  },
  rejectReasonLabel: {
    fontSize: "0.8125rem",
    fontWeight: 700,
    color: "var(--hb-angel-urgent)",
  },
});
