import * as stylex from "@stylexjs/stylex";

const DESKTOP = "@media (min-width: 768px)";

export const styles = stylex.create({
  // Two-pane layout: media on the left, content + comments on the right.
  pane: {
    position: "relative",
    display: "flex",
    flexDirection: { default: "column", [DESKTOP]: "row" },
    alignItems: { [DESKTOP]: "stretch" },
    flex: 1,
    minHeight: 0,
    maxHeight: { [DESKTOP]: "82vh" },
    borderRadius: "inherit",
    overflow: "hidden",
  },
  media: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#000",
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
    flex: { [DESKTOP]: "1 1 0" },
  },
  side: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    minHeight: { default: 300, [DESKTOP]: 440 },
    flex: { [DESKTOP]: "0 0 340px" },
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 14,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--hb-color-border)",
  },
  textWrap: { display: "flex", flexDirection: "column", gap: 4, padding: 14 },
  // Fills the space between the caption and the composer (which stays pinned at
  // the bottom), scrolling when the thread is long.
  commentsList: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    paddingInline: 14,
    paddingBlock: 12,
    overflowY: "auto",
    minHeight: 0,
  },
  text: {
    margin: 0,
    fontSize: "0.9375rem",
    lineHeight: 1.6,
    color: "var(--hb-color-text-primary)",
    whiteSpace: "pre-line",
  },
  textClamp: {
    display: "-webkit-box",
    WebkitLineClamp: 4,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  more: {
    alignSelf: "flex-start",
    padding: 0,
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    fontSize: "0.8125rem",
    fontWeight: 600,
    color: "var(--hb-color-text-secondary)",
  },
  comment: { display: "flex", gap: 6, fontSize: "0.9375rem", lineHeight: 1.5 },
  commentAuthor: { fontWeight: 700, color: "var(--hb-color-text-primary)", flexShrink: 0 },
  commentBody: { color: "var(--hb-color-text-primary)", minWidth: 0, wordBreak: "break-word" },
  empty: { fontSize: "0.875rem", color: "var(--hb-color-text-secondary)" },
  footer: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "10px 14px",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--hb-color-border)",
  },
  composer: { display: "flex", alignItems: "center", gap: 8 },
  input: {
    flex: 1,
    height: 38,
    borderRadius: 999,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    paddingInline: 14,
    fontSize: "0.9375rem",
    backgroundColor: "var(--hb-color-canvas)",
    color: "var(--hb-color-text-primary)",
  },
});
