import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: {
    maxWidth: 640,
    marginInline: "auto",
    paddingInline: "clamp(16px, 4vw, 32px)",
    paddingTop: 24,
    paddingBottom: 40,
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  title: {
    margin: 0,
    fontSize: "1.375rem",
    fontWeight: 700,
    color: "var(--hb-color-text-primary)",
  },
  field: { display: "flex", flexDirection: "column", gap: 8 },
  label: {
    fontSize: "0.8125rem",
    fontWeight: 600,
    color: "var(--hb-color-text-secondary)",
  },
  // Wraps responsively; caps at a few rows and scrolls when the viewer has many
  // signed-up events, so the composer never grows unbounded.
  options: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    maxHeight: 132,
    overflowY: "auto",
    scrollbarWidth: "none",
    "::-webkit-scrollbar": { display: "none" },
  },
  chip: {
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    paddingBlock: 8,
    paddingInline: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    backgroundColor: { default: "transparent", ":hover": "var(--hb-color-canvas)" },
    color: "var(--hb-color-text-secondary)",
    fontSize: "0.875rem",
    cursor: "pointer",
  },
  chipOn: {
    borderColor: "var(--hb-color-accent)",
    backgroundColor: "var(--hb-color-accent)",
    color: "var(--hb-color-accent-contrast)",
    fontWeight: 600,
  },
  hint: { fontSize: "0.8125rem", color: "var(--hb-color-text-secondary)" },
  attachRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  attachBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    paddingBlock: 8,
    paddingInline: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "var(--hb-color-border)",
    backgroundColor: { default: "transparent", ":hover": "var(--hb-color-canvas)" },
    color: "var(--hb-color-text-secondary)",
    fontSize: "0.875rem",
    cursor: "pointer",
  },
  hiddenInput: { display: "none" },
  thumb: { position: "relative", width: 72, height: 72 },
  thumbImg: { width: "100%", height: "100%", objectFit: "cover", borderRadius: 8, display: "block" },
  thumbRemove: {
    position: "absolute",
    insetBlockStart: -6,
    insetInlineEnd: -6,
    width: 20,
    height: 20,
    borderRadius: 999,
    borderWidth: 0,
    borderStyle: "none",
    cursor: "pointer",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    color: "#fff",
    fontSize: "0.75rem",
    lineHeight: 1,
  },
  actions: { display: "flex", justifyContent: "flex-end", gap: 8 },
});
