import * as stylex from "@stylexjs/stylex";

const REDUCE = "@media (prefers-reduced-motion: reduce)";

const fadeUp = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(12px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

export const styles = stylex.create({
  root: {
    maxWidth: 640,
    marginInline: "auto",
    paddingInline: "clamp(16px, 4vw, 32px)",
    paddingTop: 24,
    paddingBottom: 48,
    display: "flex",
    flexDirection: "column",
    gap: 24,
    animationName: fadeUp,
    animationDuration: "var(--hb-angel-dur-slow)",
    animationTimingFunction: "var(--hb-angel-ease)",
    animationFillMode: "both",
    [REDUCE]: { animationName: "none" },
  },

  // Section header: overline kicker + accent left-rule.
  header: { display: "flex", flexDirection: "column", gap: 10 },
  kicker: {
    fontSize: "0.6875rem",
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "var(--hb-color-accent-dark)",
  },
  titleRow: { display: "flex", alignItems: "center", gap: 12 },
  rule: {
    flexShrink: 0,
    width: 3,
    height: 24,
    borderRadius: "var(--hb-angel-radius-pill)",
    backgroundColor: "var(--hb-color-accent)",
  },
  title: {
    margin: 0,
    fontSize: "1.625rem",
    fontWeight: 700,
    letterSpacing: "-0.015em",
    color: "var(--hb-color-text-primary)",
  },

  field: { display: "flex", flexDirection: "column", gap: 10 },
  label: {
    fontSize: "0.875rem",
    fontWeight: 700,
    color: "var(--hb-color-text-primary)",
  },
  // Wraps responsively; caps at a few rows and scrolls when the viewer has many
  // signed-up events, so the composer never grows unbounded.
  options: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    maxHeight: 132,
    overflowY: "auto",
    scrollbarWidth: "none",
    "::-webkit-scrollbar": { display: "none" },
  },
  chip: {
    maxWidth: "100%",
    minHeight: 40,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    paddingBlock: 9,
    paddingInline: 16,
    borderRadius: "var(--hb-angel-radius-pill)",
    borderWidth: 0,
    borderStyle: "none",
    backgroundColor: { default: "var(--hb-angel-surface-alt)", ":hover": "var(--hb-angel-green-tint)" },
    color: "var(--hb-color-text-secondary)",
    fontSize: "0.875rem",
    fontWeight: 600,
    cursor: "pointer",
    transitionProperty: "background-color, color, box-shadow, transform",
    transitionDuration: "var(--hb-angel-dur-fast)",
    transitionTimingFunction: "var(--hb-angel-ease-spring)",
    ":active": { transform: "scale(0.97)" },
    ":focus-visible": { outline: "none", boxShadow: "var(--hb-angel-focus-ring)" },
    [REDUCE]: { transitionProperty: "none", ":active": { transform: "none" } },
  },
  chipOn: {
    backgroundColor: "var(--hb-color-accent)",
    color: "var(--hb-color-accent-contrast)",
    boxShadow: "var(--hb-angel-glow-accent)",
  },
  hint: {
    fontSize: "0.875rem",
    lineHeight: 1.6,
    color: "var(--hb-color-text-secondary)",
    padding: 16,
    borderRadius: "var(--hb-angel-radius-md)",
    backgroundColor: "var(--hb-angel-warm-tint)",
  },
  attachRow: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" },
  attachBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 72,
    minWidth: 72,
    paddingBlock: 8,
    paddingInline: 14,
    borderRadius: "var(--hb-angel-radius-md)",
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "var(--hb-color-border)",
    backgroundColor: { default: "var(--hb-angel-surface-alt)", ":hover": "var(--hb-angel-green-tint)" },
    color: "var(--hb-color-text-secondary)",
    fontSize: "0.8125rem",
    fontWeight: 600,
    textAlign: "center",
    cursor: "pointer",
    transitionProperty: "background-color, border-color",
    transitionDuration: "var(--hb-angel-dur-fast)",
    ":hover": { borderColor: "var(--hb-color-accent)" },
  },
  hiddenInput: { display: "none" },
  thumb: { position: "relative", width: 72, height: 72 },
  thumbImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    borderRadius: "var(--hb-angel-radius-md)",
    display: "block",
    boxShadow: "var(--hb-angel-shadow-sm)",
  },
  thumbRemove: {
    position: "absolute",
    insetBlockStart: -6,
    insetInlineEnd: -6,
    width: 22,
    height: 22,
    borderRadius: "var(--hb-angel-radius-pill)",
    borderWidth: 0,
    borderStyle: "none",
    cursor: "pointer",
    backgroundColor: "var(--hb-angel-green-deep)",
    color: "#ffffff",
    fontSize: "0.8125rem",
    lineHeight: 1,
    boxShadow: "var(--hb-angel-shadow-sm)",
  },
  actions: { display: "flex", justifyContent: "flex-end", gap: 8 },
});
