import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: {
    maxWidth: 720,
    marginInline: "auto",
    paddingInline: "clamp(16px, 4vw, 32px)",
    paddingTop: 16,
    paddingBottom: 40,
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  header: { display: "flex", flexDirection: "column", gap: 6 },
  title: {
    margin: 0,
    fontSize: "1.5rem",
    fontWeight: 700,
    color: "var(--hb-color-text-primary)",
  },
  profile: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    flexWrap: "wrap",
  },
  identity: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 4 },
  nameRow: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  nickname: {
    margin: 0,
    fontSize: "1.1875rem",
    fontWeight: 700,
    color: "var(--hb-color-text-primary)",
  },
  email: { margin: 0, fontSize: "0.9375rem", color: "var(--hb-color-text-secondary)" },
  section: { display: "flex", flexDirection: "column", gap: 10 },
  sectionTitle: {
    margin: 0,
    fontSize: "0.9375rem",
    fontWeight: 700,
    color: "var(--hb-color-text-secondary)",
  },
  actions: {
    display: "flex",
    flexDirection: "column",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--hb-color-border)",
    borderRadius: "var(--hb-angel-radius-card)",
    overflow: "hidden",
  },
  actionRow: {
    display: "flex",
    alignItems: "center",
    paddingInline: 20,
    paddingBlock: 16,
    fontSize: "0.9375rem",
    textAlign: "start",
    cursor: "pointer",
    borderWidth: 0,
    borderStyle: "none",
    borderBottomWidth: { default: 1, ":last-child": 0 },
    borderBottomStyle: "solid",
    borderBottomColor: "var(--hb-color-border)",
    color: "var(--hb-color-text-primary)",
    backgroundColor: { default: "transparent", ":hover": "var(--hb-color-canvas)" },
    textDecoration: "none",
  },
  danger: { color: "var(--hb-color-error, #d32f2f)" },
});
