import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  grid: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
  },
  thumb: {
    position: "relative",
    width: 92,
    height: 92,
    borderRadius: "var(--hb-angel-radius-md)",
    overflow: "hidden",
    boxShadow: "var(--hb-angel-shadow-sm)",
    backgroundColor: "var(--hb-angel-surface-alt)",
  },
  thumbImg: { width: "100%", height: "100%", objectFit: "cover" },
  remove: {
    position: "absolute",
    top: 4,
    insetInlineEnd: 4,
    width: 22,
    height: 22,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    borderRadius: "50%",
    cursor: "pointer",
    fontSize: "0.9375rem",
    lineHeight: 1,
    color: "var(--hb-angel-on-photo)",
    backgroundColor: {
      default: "var(--hb-angel-disc-scrim)",
      ":hover": "var(--hb-angel-disc-scrim-strong)",
    },
    backdropFilter: "blur(6px)",
    WebkitBackdropFilter: "blur(6px)",
  },
  addTile: {
    width: 92,
    height: 92,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "var(--hb-angel-radius-md)",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "var(--hb-color-border)",
    backgroundColor: { default: "var(--hb-color-surface)", ":hover": "var(--hb-angel-surface-alt)" },
    cursor: "pointer",
    fontSize: "0.8125rem",
    fontWeight: 600,
    color: "var(--hb-color-text-secondary)",
    textAlign: "center",
  },
  hiddenInput: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    border: 0,
  },
});
