import * as stylex from "@stylexjs/stylex";

const DESKTOP = "@media (min-width: 768px)";

export const styles = stylex.create({
  shell: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
    backgroundColor: "var(--hb-color-surface)",
    color: "var(--hb-color-text-primary)",
  },
  bar: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    backgroundColor: "rgba(255, 255, 255, 0.86)",
    backdropFilter: "saturate(1.4) blur(10px)",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--hb-color-border)",
  },
  barInner: {
    maxWidth: 1120,
    marginInline: "auto",
    paddingInline: "clamp(16px, 4vw, 40px)",
    height: 64,
    display: "flex",
    alignItems: "center",
    gap: 16,
  },
  brand: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontWeight: 700,
    fontSize: "1.125rem",
    letterSpacing: "-0.01em",
    color: "var(--hb-color-text-primary)",
  },
  nav: {
    display: { default: "none", [DESKTOP]: "flex" },
    alignItems: "center",
    gap: 28,
    marginLeft: 8,
  },
  navLink: {
    fontSize: "0.9375rem",
    fontWeight: 500,
    color: { default: "var(--hb-color-text-secondary)", ":hover": "var(--hb-color-accent-dark)" },
  },
  actions: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 8 },
  burger: {
    display: { default: "inline-flex", [DESKTOP]: "none" },
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    borderWidth: 0,
    borderRadius: 10,
    backgroundColor: { default: "transparent", ":hover": "var(--hb-angel-green-tint)" },
    color: "var(--hb-color-text-primary)",
    fontSize: "1.25rem",
    cursor: "pointer",
  },
  mobileNav: {
    display: { default: "flex", [DESKTOP]: "none" },
    flexDirection: "column",
    paddingInline: 20,
    paddingBottom: 12,
    gap: 2,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--hb-color-border)",
  },
  mobileLink: {
    paddingBlock: 12,
    fontSize: "0.9375rem",
    fontWeight: 500,
    color: "var(--hb-color-text-primary)",
  },
  main: { flex: 1 },
  footer: {
    marginTop: 72,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--hb-color-border)",
    backgroundColor: "var(--hb-angel-surface-alt)",
  },
  footerInner: {
    maxWidth: 1120,
    marginInline: "auto",
    paddingBlock: 20,
    paddingInline: "clamp(16px, 4vw, 40px)",
  },
});
